#spring:
#  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:8181"
#            allowedHeaders: "*"
#            allowedMethods:
#              - GET
#              - POST